<?php
// $Id$

function postblock_theme() {
  return array(
    'postblock_item' => array(
      'arguments' => array('type_info' => NULL),
      'template' => 'postblock-item',
    ),
    'postblock' => array(
      'arguments' => array('items' => array()),
    ),
  );
}

function postblock_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['post'] = array(
      'info' => t('Post content'),
      'weight' => -1,
      'status' => 1,
      'region' => 'right',
      'cache' => BLOCK_CACHE_PER_ROLE,
    );
    return $blocks;
  }
  else if ($op == 'configure' && $delta == 'post') {
    $form['postblock_hidden_types'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Hide the following content types'),
      '#default_value' => variable_get('postblock_hidden_types', array()),
      '#options' => node_get_types('names'),
    );
    return $form;
  }
  else if ($op == 'save' && $delta == 0) {
    variable_set('postblock_hidden_types', $edit['postblock_hidden_types']);
  }
  else if ($op == 'view' && $delta == 'post') {
    $block = array(
      'subject' => t('Post content'),
      'content' => postblock_generate_block(),
    );
    return $block;
  }
}

function postblock_generate_block() {
  $hidden_types = variable_get('postblock_hidden_types', array());
  $all_types = node_get_types('types');
  $list = array();
  
  foreach($all_types as $key => $value) {
    if (empty($hidden_types[$key]) && node_access('create', $key)) {
      $list[] = $value;
    }
  }
  if (!empty($list)) {
    return theme('postblock', $list);
  }
}

function theme_postblock($items = array()) {
  foreach ($items as $item) {
    $links[] = l(t('Create a !type', array('!type' => $item->name)), 'node/add/' . $item->type);
  }
  return theme('item_list', $links, NULL, 'ul', array('id' => 'postblock-items'));
}

function postblock_preprocess_postblock_item(&$vars) {
  drupal_add_css(drupal_get_path('module', 'postblock') . '/postblock.css');
  
  $type_info = $vars['type_info'];
  $vars['type'] = $type_info->type;
  $vars['name'] = $type_info->name;
  $vars['description'] = empty($type_info->description) ? NULL : check_markup($type_info->description);
  $vars['help'] = empty($type_info->help) ? NULL : check_markup($type_info->help);
  $vars['url'] = url('node/add/' . $type_info->type);
  $vars['type_class'] = str_replace('_', '-', $type_info->type);
}

